- name: Skip IPSec role when transport mode is not ipsec
  meta: end_host
  when: not ipsec_enabled

- name: Include IPSec v2 precheck stage
  include_tasks: precheck.yml

- name: Include IPSec v2 prepare stage
  include_tasks: prepare.yml

- name: Include IPSec v2 apply stage
  include_tasks: apply.yml

- name: Include IPSec v2 validate stage
  include_tasks: validate.yml
